GET http://localhost:3003/api/blogs
####
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "name": "Top 10 Blogs",
  "author": "Humphrey Bloggart",
  "url": "www.casablogca",
  "likes": 1500000
}

