GET http://localhost:3003/api/blogs
####
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
 "title": "How to blog",
 "author": "bloggert",
"url" : "www.foo.com"
}

####
DELETE http://localhost:3003/api/blogs/621daacf925f2446a907de8b